name: microvm-kernel

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  microvm-kernel:
    runs-on: [actuated-arm64-32cpu-64gb]
    steps:

# vmmeter start
      - uses: alexellis/setup-arkade@master
      - name: Install vmmeter
        run: |
          sudo -E arkade oci install ghcr.io/openfaasltd/vmmeter:latest --path /usr/local/bin/
      - uses: self-actuated/vmmeter-action@master
  # vmmeter end

      - name: free RAM
        run: free -h
      - name: List CPUs
        run: nproc
      - name: get build toolchain
        run: |
          sudo apt update -qy
          sudo apt-get install -qy \
            git \
            build-essential \
            fakeroot \
            libncurses5-dev \
            libssl-dev \
            ccache \
            bison \
            flex \
            libelf-dev \
            dwarves \
            bc
      - name: clone linux
        run: |
          time git clone https://github.com/torvalds/linux.git linux.git --depth=1 --branch v6.0
      - name: make config
        run: |
          cd linux.git 
          scripts/config --disable SYSTEM_TRUSTED_KEYS
          scripts/config --disable SYSTEM_REVOCATION_KEYS
          make oldconfig

      - name: Make vmlinux
        run: |
          cd linux.git
          time make vmlinux -j$(nproc)
          du -h ./vmlinux
